AY2324S2-CS2103T-W11-3/tp

- docs/_config.yml
- docs/_sass/minima/_base.scss
- docs/index.md
> Update site headers to match project name

- docs/DeveloperGuide.md
> Update product scope in the docs

- docs/AboutUs.md
- docs/_config.yml
- docs/index.md
Update index.md to contain correct information
Update AboutUs.md for responsibilities close #30
> Update config.yml to point website link to correct location.

- docs/DeveloperGuide.md
- Included detailed Non-Functional Requirements focusing on performance, scalability, and logging.
- Add comprehensive use cases for booking system operations, including booking, viewing and cancelling consultations. clear #32
> docs: Add NFRs and use cases to Developer Guide

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/BookCommand.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/booking/Booking.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
Closes #41 and creates the BookCommand class and its dependencies to be used in other parts of the code.
TODOS:
-[ ] flesh out Booking class #38 
-[ ] fix up Messages.format(Booking) {waiting on above before this can be done}
-[ ] implement ModelManager.addBooking() method #42
> Add BookCommand class

- src/main/java/seedu/address/ui/HelpWindow.java
- src/main/resources/view/HelpWindow.fxml
> Fix help message to show correct user guide

- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/ui/BookingCard.java
- src/main/java/seedu/address/ui/BookingListPanel.java
- src/main/java/seedu/address/ui/CommandBox.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/resources/view/BookingListCard.fxml
- src/main/resources/view/BookingListPanel.fxml
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/PersonListCard.fxml
- src/main/resources/view/ResultDisplay.fxml
- src/main/resources/view/styleSheets/DarkTheme.css
Changed UI colors and added Booking List
close #37
> Improve UI and add Booking List Card and Panel

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/ClearCommand.java
> Fix bug in ClearCommand where bookings will also be deleted along with

- src/main/java/seedu/address/MainApp.java
> Fix app crash when no datafile/folder

- docs/diagrams/ModelClassDiagram.puml
> Update ModelClass UML diagram to reflect new codebase

- src/main/java/seedu/address/commons/core/GuiSettings.java
- src/main/java/seedu/address/commons/core/Theme.java
- src/main/java/seedu/address/logic/commands/CommandResult.java
- src/main/java/seedu/address/logic/commands/ThemeCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/logic/parser/ThemeCommandParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
- src/main/java/seedu/address/model/UserPrefs.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/styleSheets/DarkTheme.css
- src/main/resources/view/styleSheets/LightTheme.css
change theme with theme -bg dark/light
> Add Theme command to change themes

- docs/diagrams/UiClassDiagram.puml
Updated the Ui Class diagram to include Booking List
close #92
> Update UML diagram for Ui Component

- docs/UserGuide.md
- src/test/java/seedu/address/commons/core/GuiSettingsTest.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/BookCommandTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
- src/test/java/seedu/address/storage/StorageManagerTest.java
Removed Default GuiSettings constructors in test files and replace with a more suitable alternative
> Add test coverage to GuiSettings

- build.gradle
- docs/AboutUs.md
- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/CancelCommand.java
- src/main/java/seedu/address/model/booking/Booking.java
- src/test/java/seedu/address/logic/commands/CancelCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/testutil/TypicalIndexes.java
Previously message shown on cancellation was incorrect, message was modified in this commit to reflect that the booking is cancelled correctly.
> Add minor fix in CancelCommand

- docs/UserGuide.md
Minor fix to include the image in the user guide proper
> Fix incorrect path name for DeleteCommandContactsSuccess.png

- docs/UserGuide.md
This commit moves sub-section headers to the right sections
Closes #187
> Fix UG formatting issues

- src/main/java/seedu/address/logic/commands/BookCommand.java
- src/main/java/seedu/address/logic/parser/BookCommandParser.java
- src/main/java/seedu/address/model/booking/Booking.java
- src/main/java/seedu/address/model/booking/EndTime.java
- src/main/java/seedu/address/model/booking/StartTime.java
- src/test/java/seedu/address/logic/parser/BookCommandParserTest.java
- src/test/java/seedu/address/model/booking/EndTimeTest.java
- src/test/java/seedu/address/model/booking/StartTimeTest.java
- src/test/java/seedu/address/testutil/TypicalBookings.java
Fixes booking date related bugs #142 and #143
> Fix booking date bugs

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/ProfCommand.java
- src/main/java/seedu/address/model/person/Address.java
- src/main/java/seedu/address/model/person/Email.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/Phone.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
Reverts AY2324S2-CS2103T-W11-3/tp#201
> Revert "Fix various messages and documentation bugs"

- docs/UserGuide.md
> Small fix for ug closes #193

- docs/DeveloperGuide.md
Minor commit to fix DG table formatting as it is not correctly formatted on browser. This fix introduces the change which hopefully reverts it to normal
> Fix DG table formatting

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/ProfCommand.java
This commit introduces more Back to ToC hyperlinks and correctly fixes the `add` and `update` and `edit` hyperlinks for better navigation
> Update and add more hyperlinks in UG

- docs/UserGuide.md
Update some minor grammatical mistakes
> Fix table formatting on UserGuide

- docs/UserGuide.md
Current formatting on web browser is still not correct, this minor commit introduces this fix
> Reformat table to work in web browser

- docs/UserGuide.md
`prof -a` command. Add another content box for Caution and additionally fixed some grammatical errors
> Add more information to UserGuide regarding unexpected behaviors of

- src/main/java/seedu/address/ui/CommandBox.java
This change now fix the previous issues
> [bug]: Fix caret issues in Command Box

- docs/UserGuide.md
Added more information for users to follow as well as updated certain command formats in the UG.
> Fix final mistakes in UserGuide

- docs/UserGuide.md
Make formatting on web browser look better to the user
> Add page breaks to UserGuide
